algrin_article_article_api:
    resource: "@AlgrinArticleBundle/Controller/ArticleRESTController.php"
    type:   rest

algrin_article:
    resource: "@AlgrinArticleBundle/Controller/"
    type:     annotation
    prefix:   /
