<?php

namespace Algrin\ArticleBundle\Repository;
use Algrin\ArticleBundle\Entity\Article;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string    $slug
     * @return Article
     */
    public function getByIdOrSlug($slug) {
        $qb = $this->createQueryBuilder('a');
        $qb->where('a.id = :id')->setParameter('id', $slug);
        $qb->orWhere('a.slug = :slug')->setParameter('slug', $slug);
        return $qb->getQuery()->getOneOrNullResult();
    }
}
